track_order_task:
  description: "Track the status of a customer's order and provide detailed shipping information."
  expected_output: "Current order status with tracking details and estimated delivery"
  agent_role: "Order Tracking Specialist"
  tools: ["OrderTrackingTool"]
  
style_recommendation_task:
  description: "Analyze customer preferences and recommend suitable home decor products"
  expected_output: "List of recommended products with explanations for why they match the customer's style"
  agent_role: "Style Advisor"
  tools: ["StyleAdvisorTool"]

return_process_task:
  description: "Provide clear instructions on how to initiate a return, including any necessary policy details."
  expected_output: "A detailed, step-by-step guide on the return process, including eligibility criteria and refund options."
  agent_role: "Returns Specialist"
  tools: ["ReturnsTool"]

product_info_task:
  description: "Answer a customer's query about a specific product's details. You must use the Product Info Tool to find the information."
  expected_output: "A concise and accurate response containing the product's dimensions, materials, and other relevant details."
  agent_role: "Product Information Specialist"
  tools: ["ProductInfoTool"]